### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Bot'

### ISSUE THREAD

**Issue by nightgardens** [notsniped/discord-snipe-bot#21]
File "c:\Users\jcbri\Downloads\discord-snipe-bot-main\Main.py", line 20, in <module>
    client = discord.Bot()  # READ COMMENT AT LINE 13 FOR MORE INFO
             ^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'Bot'

Installed bat, pasted bot token in json, pasted username in main.py, then ran in cmd. 

![image](https://github.com/notsniped/discord-snipe-bot/assets/101486710/411a844b-2408-47ec-9a82-82130a66120d)

**Comment by nightgardens** [comment]
im idiot

**Comment by notsniped** [comment]
Lol it's okay.

I'll add the library directly in the next release.

**Comment by notsniped** [comment]
Anyway it's a wrong library issue, you should have PyCord installed instead of discord.py

`python -m pip install py-cord`
